### ISSUE TITLE
Error after updating to 5.0.4 - Feathers2

### ISSUE THREAD

**Issue by ghayne** [adafruit/Adafruit_CircuitPython_MiniMQTT#73]
After updating to 5.0.4 on my Feathers2 I am getting the following error, the code was working on 5.0.0.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "codeold.py", line 86, in <module>
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 437, in connect
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 235, in _get_connect_socket
AttributeError: 'NoneType' object has no attribute 'info'

**Comment by brentru** [comment]
@ghayne  What version of CircuitPython are you running on 5.0.4?

What does your `codeold.py` look like (what function call is it failing on?)

**Comment by ghayne** [comment]
@brentru CircuitPython 6.2.0-beta.3 - I tried -beta-2 too.

It,s failing on
 `mqtt_client.connect()`

Connecting to a local MQTT server on port 1883 with parameters:

mqtt_client = MQTT.MQTT(
    broker=secrets["broker"],
    port=secrets["port"],
    socket_pool=pool
)

**Comment by brentru** [comment]
Try:

```
mqtt_client = MQTT.MQTT(
    broker=secrets["broker"],
    port=secrets["port"],
    is_ssl=False,
    socket_pool=pool
)```

**Comment by ghayne** [comment]
Same error I'm afraid!

**Comment by lubarb** [comment]
I'm getting the same error. I edited a copy of adafruit_minimqtt.py to remove the eight lines most recently added, and the error goes away.

Using:
```
# Set up a MiniMQTT Client
mqtt_client = MQTT.MQTT(
    broker=secrets["mqtt_broker"],
    port=secrets["mqtt_port"],
    username=secrets["mqtt_username"],
    password=secrets["mqtt_password"],
    socket_pool=pool,
    ssl_context=ssl.create_default_context(),
)
```

**Comment by bangell** [comment]
I think i know what this might be.

Im using an insecure port and no logger and it fails because":

line 230:
        if self.logger and port == MQTT_TLS_PORT:
            self.logger.info(
                "Establishing a SECURE SSL connection to {0}:{1}".format(host, port)
            )
        else:
            self.logger.info(
                "Establishing an INSECURE connection to {0}:{1}".format(host, port)
            )

the problem is the else doesnt check if there is a logger, it crashes becaule logger is none

the work around is to add a logger and it works

Brian

**Comment by lubarb** [comment]
posslbly:

elif self.logger

instead of else?

**Comment by wx-watch** [comment]
Thanks for posting this!

Adding 

elif self.logger 

worked for me. For whatever reason (I'm new to this) configuring a logger for my code.py worked, but still failed for the MQTT module.

**Comment by ghayne** [comment]
@wx-watch - did you pass the logger to minimqtt like this:

```
import adafruit_logging as logging

mqtt_client = MQTT.MQTT(
    broker=secrets["broker"],
    port=secrets["port"], # Port 1883
    is_ssl=False,
    socket_pool=pool

# Define callbacks etc

mqtt_client.enable_logger(logging)
mqtt_client.connect()
```

**Comment by lubarb** [comment]
@wx-watch - on further consideration the code:

```
        if self.logger :
            if port == MQTT_TLS_PORT:
                self.logger.info(
                    "Establishing a SECURE SSL connection to {0}:{1}".format(host, port)
                )
            else:
                self.logger.info(
                    "Establishing an INSECURE connection to {0}:{1}".format(host, port)
                )

```
is functionally the same but more clearly reflects what's being done.

**Comment by wx-watch** [comment]
@ghayne Ah! First time using a logger here. I had not done:
mqtt_client.enable_logger(logging) 

...and now it works with the original code. Thanks all!

**Comment by brentru** [comment]
@ghayne  I do not see this issue anymore since updating to 5.0.5 - do you still see the issue? I tested on an ESP32-S2 Metro and ESP32-S2 MagTag with the _latest_ version of this library

**Comment by ghayne** [comment]
@brentru I missed the update, I'll try it tomorrow. I hate timezones :)

**Comment by ghayne** [comment]
@brentru I couldn't resist trying it - works perfectly, thank you. I'll close the issue.
